version: '3.1'
services:
  cartoons:
    image: in.stackroute.apps.rest:1.0.0-SNAPSHOT
    build: ./rest/
    environment:
      spring.datasource.url: jdbc:mysql://mysql/app
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: app
